trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Node Dependencies'

- script: |
    npm test
  displayName: 'Run WebdriverIO Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit-report/*.xml'
    testRunTitle: 'WebdriverIO-Mocha Execution Report'